[package]
name = "librespot-protocol"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
protobuf = "1.0.10"

[features]
with-proto-crc = []
default = ["with-proto-crc"]
